"""
Haven Health Agent - AI Patient Safety Monitor

A single, focused AI agent that monitors patient health in clinical trials,
analyzes vital signs and behavior using Claude AI, and provides real-time
alerts and insights to medical staff.

Built for the Haven clinical trial monitoring system.
"""
import os
from uagents import Agent, Context, Protocol, Model
from uagents_core.contrib.protocols.chat import (
    ChatMessage, ChatAcknowledgement, TextContent,
    StartSessionContent, EndSessionContent, chat_protocol_spec
)
from datetime import datetime
from typing import Dict, List, Optional
from uuid import uuid4
from pydantic import BaseModel
import json

# Configuration
MAILBOX_KEY = os.getenv("AGENT_MAILBOX_KEY", "")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")

# ==================== DATA MODELS ====================

class PatientUpdate(Model):
    """Patient health update from Haven CV system"""
    patient_id: str
    vitals: dict  # HR, temp, BP, SpO2
    cv_metrics: dict  # distress, movement, posture
    timestamp: str

class HealthAlert(BaseModel):
    """Health alert generated by agent"""
    alert_id: str
    patient_id: str
    severity: str  # CRITICAL, WARNING, NORMAL
    message: str
    reasoning: str
    recommended_action: str
    timestamp: str

# ==================== AGENT SETUP ====================

agent = Agent(
    name="haven_health_agent",
    seed="haven_health_secure_seed_2024",
    mailbox=f"{MAILBOX_KEY}@https://agentverse.ai" if MAILBOX_KEY else None
)

# ==================== STATE ====================

patients: Dict[str, Dict] = {}  # {patient_id: latest_data}
alerts: List[HealthAlert] = []
alert_history: List[Dict] = []

print(f"🏥 Haven Health Agent initialized")
print(f"📍 Address: {agent.address}")
print(f"📬 Mailbox: {'Enabled' if MAILBOX_KEY else 'Local'}")

# ==================== HELPER FUNCTIONS ====================

def _analyze_patient_with_claude(patient_data: Dict) -> Dict:
    """Use Claude to analyze patient health (simplified for now)"""
    # For demo/Agentverse: Use rule-based analysis
    # In production: Call actual Claude API
    
    vitals = patient_data.get("vitals", {})
    cv = patient_data.get("cv_metrics", {})
    
    hr = vitals.get("heart_rate", 70)
    temp = vitals.get("temperature", 37.0)
    bp_sys = vitals.get("blood_pressure_systolic", 120)
    spo2 = vitals.get("spo2", 98)
    distress = cv.get("distress_score", 0)
    
    # Severity assessment
    severity = "NORMAL"
    concerns = []
    
    if hr > 120 or hr < 50:
        severity = "WARNING"
        concerns.append("abnormal_heart_rate")
    
    if temp > 38.5:
        severity = "WARNING"
        concerns.append("fever")
    
    if spo2 < 90:
        severity = "CRITICAL"
        concerns.append("low_oxygen")
    
    if distress > 7:
        severity = "WARNING" if severity == "NORMAL" else "CRITICAL"
        concerns.append("high_distress")
    
    # Recommended actions
    if severity == "CRITICAL":
        action = "Immediate medical intervention required - notify physician and prepare emergency response"
    elif severity == "WARNING":
        action = "Monitor closely and prepare for potential intervention"
    else:
        action = "Continue routine monitoring"
    
    # Reasoning
    reasoning = f"HR: {hr} bpm, Temp: {temp}°C, SpO2: {spo2}%, Distress: {distress}/10"
    if concerns:
        reasoning += f". Concerns: {', '.join(concerns)}"
    
    return {
        "severity": severity,
        "concerns": concerns,
        "recommended_action": action,
        "reasoning": reasoning,
        "confidence": 0.85
    }

def _create_alert(patient_id: str, analysis: Dict) -> HealthAlert:
    """Create a health alert from analysis"""
    severity = analysis["severity"]
    
    if severity == "CRITICAL":
        message = f"🚨 CRITICAL: Patient {patient_id} requires immediate attention"
    elif severity == "WARNING":
        message = f"⚠️ WARNING: Patient {patient_id} showing concerning signs"
    else:
        message = f"✅ Patient {patient_id} status normal"
    
    return HealthAlert(
        alert_id=str(uuid4())[:8],
        patient_id=patient_id,
        severity=severity,
        message=message,
        reasoning=analysis["reasoning"],
        recommended_action=analysis["recommended_action"],
        timestamp=datetime.utcnow().isoformat()
    )

# ==================== PATIENT MONITORING PROTOCOL ====================

health_protocol = Protocol(name="HealthMonitoring", version="1.0")

@health_protocol.on_message(model=PatientUpdate)
async def handle_patient_update(ctx: Context, sender: str, msg: PatientUpdate):
    """Receive patient data from Haven system and analyze"""
    ctx.logger.info(f"📊 Update received for {msg.patient_id}")
    
    # Store patient data
    patients[msg.patient_id] = {
        "vitals": msg.vitals,
        "cv_metrics": msg.cv_metrics,
        "last_update": msg.timestamp,
        "sender": sender
    }
    
    # Analyze with Claude (or rule-based for demo)
    analysis = _analyze_patient_with_claude(patients[msg.patient_id])
    
    # Create alert if needed
    alert = _create_alert(msg.patient_id, analysis)
    
    # Store alert
    alert_history.append({
        "timestamp": alert.timestamp,
        "patient_id": alert.patient_id,
        "severity": alert.severity,
        "alert": alert.dict()
    })
    
    # Keep active alerts
    if alert.severity in ["CRITICAL", "WARNING"]:
        alerts.append(alert)
        ctx.logger.warning(f"{alert.severity}: {msg.patient_id}")
    else:
        ctx.logger.info(f"✅ {msg.patient_id} stable")
    
    # Clean up old alerts (keep last 10)
    if len(alerts) > 10:
        alerts.pop(0)

agent.include(health_protocol, publish_manifest=True)

# ==================== CHAT PROTOCOL ====================

chat_proto = Protocol(spec=chat_protocol_spec)

def create_text_chat(text: str) -> ChatMessage:
    """Create chat message"""
    return ChatMessage(
        timestamp=datetime.utcnow(),
        msg_id=uuid4(),
        content=[TextContent(type="text", text=text)]
    )

@chat_proto.on_message(ChatMessage)
async def handle_chat(ctx: Context, sender: str, msg: ChatMessage):
    """Handle chat queries about patient health"""
    ctx.logger.info(f"💬 Chat from {sender[:8]}...")
    
    # Always acknowledge
    await ctx.send(sender, ChatAcknowledgement(
        timestamp=datetime.utcnow(),
        acknowledged_msg_id=msg.msg_id
    ))
    
    response_text = ""
    
    for item in msg.content:
        if isinstance(item, StartSessionContent):
            response_text = (
                "Hello! I'm the Haven Health Agent. I monitor patients in clinical trials "
                "and alert staff to health concerns. Ask me about patient status, alerts, "
                "or specific patients!"
            )
        
        elif isinstance(item, TextContent):
            query = item.text.lower()
            
            # List all patients
            if "patients" in query or "list" in query or "who" in query:
                if patients:
                    response_text = f"👥 Monitoring {len(patients)} patient(s):\n\n"
                    for pid, data in patients.items():
                        last_update = data.get("last_update", "unknown")
                        response_text += f"• {pid} (updated: {last_update[:19]})\n"
                else:
                    response_text = "No patients currently monitored. Waiting for data from Haven system."
            
            # Status overview
            elif "status" in query or "overview" in query:
                critical = sum(1 for a in alerts if a.severity == "CRITICAL")
                warning = sum(1 for a in alerts if a.severity == "WARNING")
                
                response_text = f"🏥 System Status:\n\n"
                response_text += f"• Patients Monitored: {len(patients)}\n"
                response_text += f"• Active Alerts: {len(alerts)}\n"
                
                if critical > 0:
                    response_text += f"• 🚨 CRITICAL: {critical}\n"
                if warning > 0:
                    response_text += f"• ⚠️ WARNING: {warning}\n"
                
                if not alerts:
                    response_text += "\n✅ All patients stable"
            
            # Specific patient query
            elif any(char.isdigit() for char in query):
                # Extract patient ID
                patient_id = None
                for pid in patients.keys():
                    if pid.lower() in query:
                        patient_id = pid
                        break
                
                if patient_id and patient_id in patients:
                    data = patients[patient_id]
                    vitals = data.get("vitals", {})
                    cv = data.get("cv_metrics", {})
                    
                    response_text = f"📋 {patient_id} Status:\n\n"
                    response_text += f"Vitals:\n"
                    response_text += f"• HR: {vitals.get('heart_rate', 'N/A')} bpm\n"
                    response_text += f"• Temp: {vitals.get('temperature', 'N/A')}°C\n"
                    response_text += f"• SpO2: {vitals.get('spo2', 'N/A')}%\n"
                    response_text += f"• Distress: {cv.get('distress_score', 'N/A')}/10\n"
                    
                    # Recent alert
                    patient_alerts = [a for a in alerts if a.patient_id == patient_id]
                    if patient_alerts:
                        latest = patient_alerts[-1]
                        response_text += f"\nLatest Alert: {latest.severity}\n"
                        response_text += f"Action: {latest.recommended_action}"
                else:
                    response_text = f"No data for that patient. Try 'list patients' to see who I'm monitoring."
            
            # Alerts
            elif "alert" in query or "warning" in query or "critical" in query:
                if alerts:
                    response_text = f"🚨 Active Alerts ({len(alerts)}):\n\n"
                    for alert in alerts[-5:]:
                        response_text += f"• {alert.patient_id}: {alert.severity}\n"
                        response_text += f"  {alert.reasoning}\n"
                else:
                    response_text = "✅ No active alerts. All patients stable."
            
            # Health concern from user (redirect)
            elif any(word in query for word in ["pain", "hurt", "sick", "help", "emergency"]):
                response_text = (
                    "⚠️ If you need medical help:\n"
                    "• Call 911 (emergency)\n"
                    "• Contact your healthcare provider\n\n"
                    "I monitor patients in our clinical trial system. "
                    "I cannot provide medical advice for personal health issues."
                )
            
            # Help
            elif "help" in query or "what can" in query:
                response_text = (
                    "🤖 Haven Health Agent - I can:\n\n"
                    "📊 Monitoring:\n"
                    "• 'list patients' - Show all monitored patients\n"
                    "• 'status' - System overview\n"
                    "• 'patient P-001' - Specific patient details\n\n"
                    "🚨 Alerts:\n"
                    "• 'show alerts' - Active health alerts\n\n"
                    "I analyze vitals and behavior from the Haven system "
                    "and alert staff to health concerns using Claude AI."
                )
            
            # Default
            else:
                response_text = (
                    f"🏥 I'm monitoring {len(patients)} patient(s) with {len(alerts)} active alert(s). "
                    "Try: 'list patients', 'status', 'show alerts', or 'help'"
                )
        
        elif isinstance(item, EndSessionContent):
            response_text = "Session ended. I'll continue monitoring patients. Stay safe! 👋"
    
    if response_text:
        await ctx.send(sender, create_text_chat(response_text))

@chat_proto.on_message(ChatAcknowledgement)
async def handle_ack(ctx: Context, sender: str, msg: ChatAcknowledgement):
    """Handle acknowledgements"""
    pass

agent.include(chat_proto, publish_manifest=True)

# ==================== PERIODIC MONITORING ====================

@agent.on_interval(period=30.0)
async def periodic_check(ctx: Context):
    """Periodic status check"""
    if patients:
        critical = sum(1 for a in alerts if a.severity == "CRITICAL")
        if critical > 0:
            ctx.logger.warning(f"🚨 {critical} CRITICAL alert(s) active")
        else:
            ctx.logger.info(f"✅ Monitoring {len(patients)} patient(s) - all stable")
    else:
        ctx.logger.info("⏳ Waiting for patient data...")

@agent.on_event("startup")
async def startup(ctx: Context):
    """Startup logging"""
    ctx.logger.info("=" * 50)
    ctx.logger.info("🏥 HAVEN HEALTH AGENT")
    ctx.logger.info("=" * 50)
    ctx.logger.info(f"📍 Address: {agent.address}")
    ctx.logger.info(f"📬 Mailbox: {'Enabled' if MAILBOX_KEY else 'Local'}")
    ctx.logger.info(f"🔗 Protocols: HealthMonitoring v1.0, Chat v0.3.0")
    ctx.logger.info("=" * 50)
    ctx.logger.info("🟢 Ready - waiting for patient data")

# ==================== MAIN ====================

if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("🏥 HAVEN HEALTH AGENT")
    print("=" * 50)
    print(f"📍 Address: {agent.address}")
    print(f"📬 Mailbox: {'Configured' if MAILBOX_KEY else 'Not configured'}")
    print("\nThis agent:")
    print("  • Monitors patient vitals and behavior")
    print("  • Analyzes health data with Claude AI")
    print("  • Generates alerts for medical staff")
    print("  • Responds to queries via ASI:One")
    print("=" * 50)
    print("🟢 Starting...\n")
    agent.run()

